### PR TITLE
Add three Gems with assets

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## Pull Request details
Added three Gems with assets:
- `RobotecAssetsOfficeRaw`: Gem with *raw* assets used to decorate office space.
- `RobotecAssetsSignsRaw`: Gem with *raw* assets of various signs (plate signs, standing signs, etc.).
- `RobotecAssetsSmallContainersRaw`: Gem with *raw* assets of various containers (barrels, canisters, buckets, etc.).

## Checklist
- [x] I updated the `README.md` document to add information about new Gem(s).
- [x] I filled in the `gem.json` file with the necessary information, including license, origin, and summary in the new Gem(s).
- [x] I checked if the folder structure and filenames follow the convention described in `README.md`.
- [x] I added the `NOTICE` file with some additional comments on the license. 
- [x] I checked if the origins of prefabs follow the convention.

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
Draft: waiting for #2 to be merged first.

**Comment by michalpelka** [comment]
Problem I can see that it requires current o3de/stabilization and cannot be built with o3de 2310.

**Review by pawelbudziszewski — COMMENTED** [review]
I'd consider adding `visual` as "underscored suffix", so instead of:

- `PlateSignRestrictedVisual.prefab` 

It would be:

- `PlateSignRestricted_Visual.prefab` 

This way we will separate prefab name from its function

**Comment by jhanca-robotecai** [comment]
I renamed the gems to follow new guidelines, I renamed the prefabs, I regenerated cmake files with `2310.3` to make the gems usable with `2310.3`. It works with both `2310.3` and `stabilization/2409`.

image

**Comment by jhanca-robotecai** [comment]
Added one more gem with `FireExtinguisherCabinet` asset

**Review by pawelbudziszewski — CHANGES_REQUESTED** [review]
All objects in which the front can be distinguished should be rotated to have X-axis forward.

**Comment by jhanca-robotecai** [comment]
Replied to your code review and (additionally) added some prefabs with static rigid bodies and colliders.

**Review by pawelbudziszewski — APPROVED** [review]

**Pull request merged**
